workflows:
  my-workflow:
    scripts:
      - name: Build Android App Bundle
        working_directory: android
        script: ./gradlew assembleDebug
    artifacts:
      - build/**/outputs/bundle/**/*.aab